##                             Writing Efficient Python Code

In [1]:
print('Hello World!')
#Pythonic code == efficient code

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%lsmagic

Available line magics:
%alias  %alias_magic  %autoawait  %autocall  %automagic  %autosave  %bookmark  %cat  %cd  %clear  %colors  %conda  %config  %connect_info  %cp  %debug  %dhist  %dirs  %doctest_mode  %ed  %edit  %env  %gui  %hist  %history  %killbgscripts  %ldir  %less  %lf  %lk  %ll  %load  %load_ext  %loadpy  %logoff  %logon  %logstart  %logstate  %logstop  %ls  %lsmagic  %lx  %macro  %magic  %man  %matplotlib  %mkdir  %more  %mv  %notebook  %page  %pastebin  %pdb  %pdef  %pdoc  %pfile  %pinfo  %pinfo2  %pip  %popd  %pprint  %precision  %prun  %psearch  %psource  %pushd  %pwd  %pycat  %pylab  %qtconsole  %quickref  %recall  %rehashx  %reload_ext  %rep  %rerun  %reset  %reset_selective  %rm  %rmdir  %run  %save  %sc  %set_env  %store  %sx  %system  %tb  %time  %timeit  %unalias  %unload_ext  %who  %who_ls  %whos  %xdel  %xmode

Available cell magics:
%%!  %%HTML  %%SVG  %%bash  %%capture  %%debug  %%file  %%html  %%javascript  %%js  %%latex  %%markdown  %%perl  %%prun  %%pypy  %%

###                                       Що виведе наступний код

In [3]:
names = ['Jerry', 'Kramer', 'Elaine', 'George', 'Newman']


i = 0
new_list= []
while i < len(names):
    if len(names[i]) >= 6:
        new_list.append(names[i])
    i += 1
    
#Which one is Pythonic

second_list = []
for name in names:
    if len(name) >= 6:
        second_list.append(name)
print(second_list)

print([name for name in names if len(name) >= 6])

['Kramer', 'Elaine', 'George', 'Newman']
['Kramer', 'Elaine', 'George', 'Newman']


In [4]:
characters = ['a','b','c','d']
index_characters = enumerate(characters)
print([*index_characters])

[(0, 'a'), (1, 'b'), (2, 'c'), (3, 'd')]


In [5]:
x = ['May','Apr','Sep']
y = [86, 93, 55]
lists = zip(x,y)
new_dict = dict(lists)
print(new_dict)

{'May': 86, 'Apr': 93, 'Sep': 55}


In [6]:
n1 = [3,5,8,1]
n2 = [n ** 2 for n in n1]
pairs = zip(n1,n2)
for idx,pair in enumerate(pairs):
    
    n,m = pair
    
    print('{} ^ {} = {}'.format(n,2,m))

3 ^ 2 = 9
5 ^ 2 = 25
8 ^ 2 = 64
1 ^ 2 = 1


**Що з переліченого є правдою про list**
1. List are unique
2. List are iterable
3. List are immutable
4. List are sets

In [7]:
marks = [1, 2, 3, 4]
for index, mark in enumerate(marks) :
    print("index " + str(index) + ": " + str(mark))

index 0: 1
index 1: 2
index 2: 3
index 3: 4


In [8]:
nums = [2,-4,6,-8,-10]
new_nums = map(abs,nums)
print([*new_nums])

[2, 4, 6, 8, 10]


In [9]:
raise_to_power = lambda x, y : x ** y
print(raise_to_power(2, 3))

8


In [10]:
#Піднести всі числа до квадрату
nums = [3,4,5,6,7]
sqrt_nums = map(lambda x: x**2,nums)
print([*sqrt_nums])

[9, 16, 25, 36, 49]


In [11]:
#Example
smt = list(range(3,20,3))
print(smt)

[3, 6, 9, 12, 15, 18]


In [12]:
smt2 = list(range(5,11))
print(smt2)

[5, 6, 7, 8, 9, 10]


In [13]:
smt3 = list(range(20))
print(smt3)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]


In [14]:
nums_list = [*range(1,12,2),*map(abs,range(-5,5))]
print(nums_list)

[1, 3, 5, 7, 9, 11, 5, 4, 3, 2, 1, 0, 1, 2, 3, 4]


In [15]:
b = [4,5,2,3]
a = map(float,b)
print(*a)

4.0 5.0 2.0 3.0


In [16]:
# Create a range function that goes from 0 to 12 with step = 3 and print the numbers
r = range (0,13,3)
print(*r)

0 3 6 9 12


In [17]:
#Вивести всі імена великими літерами
names = ['John','Alfred','Bobo','Gogo','Petro']

#names_map  = map(str.upper, names)
#names_uppercase = [*names_map]
#print(names_uppercase)

#Write this code in one line
#print(*map(str.upper, names))
#print(*map(str.upper, names))
print([*(map(str.upper,names))])

['JOHN', 'ALFRED', 'BOBO', 'GOGO', 'PETRO']


In [18]:
dict_ = dict([(1, "число 1"), (0.8, 2), ("рядок3", 3.0)])
print(dict_)

{1: 'число 1', 0.8: 2, 'рядок3': 3.0}


In [19]:
numbers = np.array([3.47, 7.54, 9.22, 1.35, 4.28])
print(numbers[numbers > 5.0])

[7.54 9.22]


In [20]:
#Вивести всі рядки 2 колонки
array = np.array([[1,2,3],
                  [4,5,6]])
print(array[:,1])

[2 5]


In [21]:
a = np.array([[1,3,5],[2,4,6]])
new_a = a ** 2
print(new_a)

[[ 1  9 25]
 [ 4 16 36]]


In [22]:
#Замінити 1 рядок значень на нові значення менші на 1
numbers = np.array([[1,3,5],
                    [2,4,6]])
numbers[0,:] = numbers[0,:] - 1
print(numbers)

[[0 2 4]
 [2 4 6]]


In [23]:
names = ['John','Alfred','Bobo','Gogo','Petro']
# чи є питання
# Create a list of arrival times
arrival_times = [*range(10,60,10)]

# Convert arrival_times to an array and update the times
arrival_times_np = np.array(arrival_times)
new_times = arrival_times_np - 3
print(new_times)
# Use list comprehension and enumerate to pair guests to new times
guest_arrivals = [(names[i],time) for i,time in enumerate(new_times)]
print(guest_arrivals)
# Map the welcome_guest function to each (guest,time) pair
#welcome_map = map(welcome_guest, guest_arrivals)
#welcome quest - Datacamp function
#guest_welcomes = [*welcome_map]
#print(guest_welcomes)
#print(*guest_welcomes, sep='\n')

[ 7 17 27 37 47]
[('John', 7), ('Alfred', 17), ('Bobo', 27), ('Gogo', 37), ('Petro', 47)]


In [24]:
students = ['std_1', 'std_2', 'std_3', 'std_4', 'std_5']
groups = ['group_1', 'group_2', 'group_3', 'group_4', 'group_5']
pairs_zip = zip(students, groups)
for std_num, group_num in pairs_zip :
    print(std_num, group_num)

std_1 group_1
std_2 group_2
std_3 group_3
std_4 group_4
std_5 group_5


In [25]:
for i, item in enumerate(pairs_zip) :
    std_num, group_num = item
    print(i, std_num, group_num)

In [26]:
%lsmagic

Available line magics:
%alias  %alias_magic  %autoawait  %autocall  %automagic  %autosave  %bookmark  %cat  %cd  %clear  %colors  %conda  %config  %connect_info  %cp  %debug  %dhist  %dirs  %doctest_mode  %ed  %edit  %env  %gui  %hist  %history  %killbgscripts  %ldir  %less  %lf  %lk  %ll  %load  %load_ext  %loadpy  %logoff  %logon  %logstart  %logstate  %logstop  %ls  %lsmagic  %lx  %macro  %magic  %man  %matplotlib  %mkdir  %more  %mv  %notebook  %page  %pastebin  %pdb  %pdef  %pdoc  %pfile  %pinfo  %pinfo2  %pip  %popd  %pprint  %precision  %prun  %psearch  %psource  %pushd  %pwd  %pycat  %pylab  %qtconsole  %quickref  %recall  %rehashx  %reload_ext  %rep  %rerun  %reset  %reset_selective  %rm  %rmdir  %run  %save  %sc  %set_env  %store  %sx  %system  %tb  %time  %timeit  %unalias  %unload_ext  %who  %who_ls  %whos  %xdel  %xmode

Available cell magics:
%%!  %%HTML  %%SVG  %%bash  %%capture  %%debug  %%file  %%html  %%javascript  %%js  %%latex  %%markdown  %%perl  %%prun  %%pypy  %%

#What is the correct syntax when using %timeit and only using 5 runs with 25 loops per each run?
timeit -runs5 -loops25 set(heroes)

%%timeit -r5 -n25 set(heroes)

%timeit set(heroes), 5, 25

%timeit -r5 -n25 set(heroes)

import sys
!{sys.executable} -m pip install memory_profiler

In [32]:
%load_ext line_profiler

In [33]:
%load_ext memory_profiler

In [35]:
# Взяти першу букву з кожного слова
names_ = ['Gogo','Jojo','Boro','Jisso']
print(*map(lambda x: x[0], names_))     


G J B J


In [36]:
#Знайти числа які повторюються в обох лістах
#Знайти числа які є в list_b і немає в list_a
list_a = [2,5,9,15,25]
list_b = [2,4,8,16,25]
set_a = set(list_a)
set_b = set(list_b)
print(set_a.intersection(set_b))
print(set_b.difference(set_a))


{25, 2}
{8, 16, 4}
